import { pool } from '../config/db';
import { fallbackStore } from '../data/fallbackStore';
import { SUBJECTS, TOPICS } from '../data/roadmapData';

export async function fastBulkSeed(closePool: boolean = false) {
  console.log('⚡ [Fast Bulk Seed] Initializing PostgreSQL schema...');

  // 1. Ensure identities are BY DEFAULT
  for (const tbl of [
    'subjects',
    'topics',
    'subtopics',
    'problems',
    'test_cases',
    'submissions',
    'user_problem_progress',
    'daily_activity',
  ]) {
    try {
      await pool.query(`ALTER TABLE "${tbl}" ALTER COLUMN id DROP IDENTITY IF EXISTS;`);
      await pool.query(`ALTER TABLE "${tbl}" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;`);
    } catch {}
  }

  // 2. Insert Subjects in 1 query
  console.log('📚 Bulk inserting subjects...');
  const subjectValues = SUBJECTS.map(
    (s) =>
      `('${s.slug}', '${s.name.replace(/'/g, "''")}', '${(s.description || '').replace(/'/g, "''")}', '${s.icon}', '${s.color_gradient}', ${s.order_index})`
  ).join(',');
  await pool.query(`
    INSERT INTO subjects (slug, name, description, icon, color_gradient, order_index)
    VALUES ${subjectValues}
    ON CONFLICT (slug) DO UPDATE SET
      name = EXCLUDED.name,
      description = EXCLUDED.description,
      icon = EXCLUDED.icon,
      color_gradient = EXCLUDED.color_gradient,
      order_index = EXCLUDED.order_index;
  `);

  const subRes = await pool.query('SELECT id, slug FROM subjects');
  const subjectMap = new Map<string, number>();
  subRes.rows.forEach((r: any) => subjectMap.set(r.slug, r.id));

  // 3. Insert Topics in 1 query
  console.log('📑 Bulk inserting topics...');
  const topicValues: string[] = [];
  for (const t of TOPICS) {
    const sId = subjectMap.get(t.subjectSlug);
    if (!sId) continue;
    topicValues.push(
      `(${sId}, '${t.name.replace(/'/g, "''")}', '${t.slug}', ${t.order_index}, '${(t.description || '').replace(/'/g, "''")}')`
    );
  }
  if (topicValues.length > 0) {
    await pool.query(`
      INSERT INTO topics (subject_id, name, slug, order_index, description)
      VALUES ${topicValues.join(',')}
      ON CONFLICT (subject_id, slug) DO UPDATE SET
        name = EXCLUDED.name,
        order_index = EXCLUDED.order_index,
        description = EXCLUDED.description;
    `);
  }

  const topRes = await pool.query('SELECT id, slug, subject_id FROM topics');
  const topicMap = new Map<string, number>();
  topRes.rows.forEach((r: any) => {
    topicMap.set(`${r.subject_id}:${r.slug}`, r.id);
    topicMap.set(r.slug, r.id);
  });

  // 4. Bulk insert Problems in chunks of 50
  const problems = (fallbackStore as any).enrichedProblems;
  console.log(`🧩 Bulk inserting ${problems.length} problems...`);

  const CHUNK_SIZE = 50;
  for (let i = 0; i < problems.length; i += CHUNK_SIZE) {
    const chunk = problems.slice(i, i + CHUNK_SIZE);
    const valuePlaceholders: string[] = [];
    const params: any[] = [];
    let pIdx = 1;

    for (const p of chunk) {
      const subjectId = subjectMap.get(p.subject_slug) || 1;
      let topicId = topicMap.get(`${subjectId}:${p.topic_slug}`) || topicMap.get(p.topic_slug) || 1;

      valuePlaceholders.push(
        `($${pIdx}, $${pIdx + 1}, $${pIdx + 2}, $${pIdx + 3}, $${pIdx + 4}, $${pIdx + 5}, $${pIdx + 6}, $${pIdx + 7}, $${pIdx + 8}, $${pIdx + 9}, $${pIdx + 10}, $${pIdx + 11}, $${pIdx + 12}, $${pIdx + 13}, $${pIdx + 14}, $${pIdx + 15}, $${pIdx + 16}::jsonb, $${pIdx + 17}::jsonb, $${pIdx + 18}::jsonb, true, false)`
      );

      params.push(
        p.id,
        p.title,
        p.slug || `problem-${p.id}`,
        p.description || p.title,
        subjectId,
        topicId,
        p.difficulty || 'EASY',
        p.level || 'BEGINNER',
        'PUBLISHED',
        p.input_format || '',
        p.output_format || '',
        p.constraints || '',
        p.sample_input || 'No input required',
        p.sample_output || '',
        p.explanation || '',
        p.starter_code || p.starter_snippets?.java || '',
        JSON.stringify(p.examples || []),
        JSON.stringify(p.hints || []),
        JSON.stringify(p.supported_languages || ['JAVA', 'PYTHON'])
      );
      pIdx += 19;
    }

    await pool.query(
      `
      INSERT INTO problems (
        id, title, slug, description, subject_id, topic_id, difficulty, level, status,
        input_format, output_format, constraints, sample_input, sample_output, explanation, starter_code,
        examples, hints, supported_languages, is_published, is_deleted
      ) VALUES ${valuePlaceholders.join(',')}
      ON CONFLICT (id) DO UPDATE SET
        title = EXCLUDED.title,
        slug = EXCLUDED.slug,
        description = EXCLUDED.description,
        subject_id = EXCLUDED.subject_id,
        topic_id = EXCLUDED.topic_id,
        difficulty = EXCLUDED.difficulty,
        level = EXCLUDED.level,
        status = EXCLUDED.status,
        input_format = EXCLUDED.input_format,
        output_format = EXCLUDED.output_format,
        constraints = EXCLUDED.constraints,
        sample_input = EXCLUDED.sample_input,
        sample_output = EXCLUDED.sample_output,
        explanation = EXCLUDED.explanation,
        starter_code = EXCLUDED.starter_code,
        examples = EXCLUDED.examples,
        hints = EXCLUDED.hints,
        supported_languages = EXCLUDED.supported_languages;
    `,
      params
    );
    console.log(`  Inserted problems batch ${i + 1} to ${Math.min(i + CHUNK_SIZE, problems.length)}...`);
  }

  // 5. Bulk insert test cases (only if test cases table is empty)
  console.log('🧪 Checking test cases...');
  const tcCheck = await pool.query('SELECT COUNT(*) as count FROM test_cases');
  const tcExistingCount = parseInt(tcCheck.rows[0]?.count || '0', 10);
  if (tcExistingCount === 0) {
    console.log('🧪 Inserting initial test cases...');

  const allTestCases: Array<{
    problem_id: number;
    input: string;
    expected_output: string;
    is_hidden: boolean;
    validation_type: string;
  }> = [];

  for (const p of problems) {
    const pub = p.public_tests || p.public_test_cases || [];
    const hid = p.hidden_tests || p.hidden_test_cases || [];
    for (const tc of pub) {
      allTestCases.push({
        problem_id: p.id,
        input: tc.input,
        expected_output: tc.expected_output || tc.output || '',
        is_hidden: false,
        validation_type: p.validation_type || 'TRIMMED',
      });
    }
    for (const tc of hid) {
      allTestCases.push({
        problem_id: p.id,
        input: tc.input,
        expected_output: tc.expected_output || tc.output || '',
        is_hidden: true,
        validation_type: p.validation_type || 'TRIMMED',
      });
    }
  }

  const TC_CHUNK = 80;
  for (let i = 0; i < allTestCases.length; i += TC_CHUNK) {
    const chunk = allTestCases.slice(i, i + TC_CHUNK);
    const placeholders: string[] = [];
    const params: any[] = [];
    let pIdx = 1;

    for (const tc of chunk) {
      placeholders.push(`($${pIdx}, $${pIdx + 1}, $${pIdx + 2}, $${pIdx + 3}, $${pIdx + 4})`);
      params.push(tc.problem_id, tc.input, tc.expected_output, tc.is_hidden, tc.validation_type);
      pIdx += 5;
    }

    await pool.query(
      `
      INSERT INTO test_cases (problem_id, input, expected_output, is_hidden, validation_type)
      VALUES ${placeholders.join(',')}
    `,
      params
    );
  }
  } else {
    console.log(`🧪 Test cases already present (${tcExistingCount}), preserving existing test cases.`);
  }

  // Update sequences
  await pool.query(
    `SELECT setval(pg_get_serial_sequence('problems', 'id'), COALESCE(MAX(id), 1)) FROM problems;`
  );
  await pool.query(
    `SELECT setval(pg_get_serial_sequence('test_cases', 'id'), COALESCE(MAX(id), 1)) FROM test_cases;`
  );
  await pool.query(
    `SELECT setval(pg_get_serial_sequence('subjects', 'id'), COALESCE(MAX(id), 1)) FROM subjects;`
  );
  await pool.query(
    `SELECT setval(pg_get_serial_sequence('topics', 'id'), COALESCE(MAX(id), 1)) FROM topics;`
  );

  const pFinal = await pool.query('SELECT COUNT(*) as c FROM problems');
  const tcFinal = await pool.query('SELECT COUNT(*) as c FROM test_cases');

  console.log(`\n🎉 [Fast Bulk Seed Complete!]`);
  console.log(`   - Problems in DB: ${pFinal.rows[0].c}`);
  console.log(`   - Test Cases in DB: ${tcFinal.rows[0].c}`);

  if (closePool) {
    await pool.end();
  }
}

if (require.main === module) {
  fastBulkSeed(true).catch((err) => {
    console.error('Fast bulk seed failed:', err);
    pool.end();
    process.exit(1);
  });
}
